export const ClaimsInitialData = [
  {
    "id": 3,
    "create_date": "2022-07-02T10:03:09.550Z",
    "id_type_claim": 1,
    "type_claim": "Заявка на подключение рабочего места новому сотруднику в офисе",
    "text": "В кабинете № 34 нужно новое рабочее место",
    "id_priority": 2,
    "priorities": "нормальный",
    "time_according_sla": 480,
    "id_state": 7,
    "state": "закрыт",
    "place_of_service": "комната 35",
    "date_time_edit_state": "2022-07-02T10:03:09.550Z",
    "date_time_close_claim": "2022-07-06T17:57:45.830Z",
    "id_autor": 1,
    "sys_number_autor": "32134",
    "autor": "Иванов Иван Иванович",
    "id_executor": 6,
    "sys_number_executor": "43221",
    "executor": "Правилов Евгений Петрович",
    "comment": "Заявка выполнена"
  },
  {
    "id": 4,
    "create_date": "2022-07-07T15:22:30.890Z",
    "id_type_claim": 2,
    "type_claim": "Заявка на смену доменного пароля",
    "text": "Изменить домен срочно",
    "id_priority": 1,
    "priorities": "критичный",
    "time_according_sla": 120,
    "id_state": 2,
    "state": "в ожидании выполнения",
    "place_of_service": "Здание 111 комната 503",
    "date_time_edit_state": "2022-07-07T15:22:30.890Z",
    "date_time_close_claim": null,
    "id_autor": 7,
    "sys_number_autor": "00001",
    "autor": "Атаманов Михаил Павлович",
    "id_executor": 6,
    "sys_number_executor": "43221",
    "executor": "Правилов Евгений Петрович",
    "comment": null
  },
  {
    "id": 5,
    "create_date": "2022-07-07T15:47:38.470Z",
    "id_type_claim": 3,
    "type_claim": "Заявка на установку специализированного ПО",
    "text": "установить  AutoCAD",
    "id_priority": 3,
    "priorities": "низкий",
    "time_according_sla": 1920,
    "id_state": 7,
    "state": "закрыт",
    "place_of_service": null,
    "date_time_edit_state": "2022-07-07T15:47:38.470Z",
    "date_time_close_claim": "2022-07-07T17:14:51.670Z",
    "id_autor": 3,
    "sys_number_autor": "34311",
    "autor": "Серебрякова Злата Бронзовна",
    "id_executor": 5,
    "sys_number_executor": "63231",
    "executor": "Воронцов Антон Борисович",
    "comment": "Заявка успешно выполнена"
  },
  {
    "id": 6,
    "create_date": "2022-07-07T17:31:44.380Z",
    "id_type_claim": 4,
    "type_claim": "Заявка на устранение ошибки ПО",
    "text": "ПО не работает, при запуске выдает ошибку и все ...",
    "id_priority": 1,
    "priorities": "критичный",
    "time_according_sla": 480,
    "id_state": 7,
    "state": "закрыт",
    "place_of_service": null,
    "date_time_edit_state": "2022-07-07T17:31:44.380Z",
    "date_time_close_claim": null,
    "id_autor": 2,
    "sys_number_autor": "65432",
    "autor": "Петров Петр Петрович",
    "id_executor": 6,
    "sys_number_executor": "43221",
    "executor": "Правилов Евгений Петрович",
    "comment": "Работа завершена"
  },
  {
    "id": 7,
    "create_date": "2022-07-07T17:38:31.690Z",
    "id_type_claim": 5,
    "type_claim": "Заявка на формирование справки по форме 2-НДФЛ",
    "text": "Оформить справку 2 НДФЛ",
    "id_priority": 3,
    "priorities": "низкий",
    "time_according_sla": 2400,
    "id_state": 2,
    "state": "в ожидании выполнения",
    "place_of_service": "Здание 100 комната 34",
    "date_time_edit_state": "2022-07-07T17:38:31.690Z",
    "date_time_close_claim": null,
    "id_autor": 3,
    "sys_number_autor": "34311",
    "autor": "Серебрякова Злата Бронзовна",
    "id_executor": 5,
    "sys_number_executor": "63231",
    "executor": "Воронцов Антон Борисович",
    "comment": null
  }
];